[package]

name = "wanderlust"
version = "0.0.1"
authors = ["Ben Brittain <ben@brittain.org>"]

[dependencies]
csv = "*"
rustc-serialize = "0.2"

[dependencies.gnuplot]
git = "https://github.com/SiegeLord/RustGnuplot.git"
